# Generated by Django 5.2 on 2025-04-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
    ]
