# Generated by Django 5.2 on 2025-04-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0002_rename_name_category_name_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statu', 'verbose_name_plural': 'Status'},
        ),
    ]
