# Generated by Django 5.2 on 2025-04-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0003_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='name_type',
        ),
    ]
