# Generated by Django 5.2 on 2025-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0008_date_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
